/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import {
    sqliteTable,
    index,
    uniqueIndex,
    foreignKey,
    integer,
    text,
    numeric,
} from "@payloadcms/db-sqlite/drizzle/sqlite-core";
import { sql, relations } from "@payloadcms/db-sqlite/drizzle";

export const orders_items = sqliteTable(
    "orders_items",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: text("id").primaryKey(),
        product: integer("product_id").references(() => products.id, {
            onDelete: "set null",
        }),
        variant_variantId: text("variant_variant_id").notNull(),
        variant_name: text("variant_name").notNull(),
        variant_price: numeric("variant_price").notNull(),
        quantity: numeric("quantity").notNull(),
        totalPrice: numeric("total_price").notNull(),
    },
    (columns) => ({
        _orderIdx: index("orders_items_order_idx").on(columns._order),
        _parentIDIdx: index("orders_items_parent_id_idx").on(columns._parentID),
        orders_items_product_idx: index("orders_items_product_idx").on(
            columns.product
        ),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [orders.id],
            name: "orders_items_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const orders = sqliteTable(
    "orders",
    {
        id: integer("id").primaryKey(),
        orderId: text("order_id").notNull(),
        user: integer("user_id").references(() => users.id, {
            onDelete: "set null",
        }),
        totalAmount: numeric("total_amount").notNull(),
        currency: text("currency").notNull(),
        paymentStatus: text("payment_status", {
            enum: ["pending", "paid", "failed", "refunded"],
        })
            .notNull()
            .default("pending"),
        orderStatus: text("order_status", {
            enum: ["pending", "processing", "shipped", "delivered", "canceled"],
        })
            .notNull()
            .default("pending"),
        paymentIntentId: text("payment_intent_id"),
        sessionId: text("session_id").notNull(),
        paymentGateway: text("payment_gateway", { enum: ["stripe"] }),
        paymentMethod: text("payment_method"),
        receiptUrl: text("receipt_url"),
        metadata: text("metadata", { mode: "json" }),
        shippingAddress: text("shipping_address", { mode: "json" }),
        billingAddress: text("billing_address", { mode: "json" }),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        orders_order_id_idx: uniqueIndex("orders_order_id_idx").on(
            columns.orderId
        ),
        orders_user_idx: index("orders_user_idx").on(columns.user),
    })
);

export const collections = sqliteTable(
    "collections",
    {
        id: integer("id").primaryKey(),
        title: text("title").notNull(),
        imageUrl: text("image_url"),
        handle: text("handle"),
        description: text("description", { mode: "json" }),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        collections_handle_idx: index("collections_handle_idx").on(
            columns.handle
        ),
        collections_updated_at_idx: index("collections_updated_at_idx").on(
            columns.updatedAt
        ),
        collections_created_at_idx: index("collections_created_at_idx").on(
            columns.createdAt
        ),
    })
);

export const products_sales_channels = sqliteTable(
    "products_sales_channels",
    {
        order: integer("order").notNull(),
        parent: integer("parent_id").notNull(),
        value: text("value", {
            enum: ["all", "onlineStore", "pos", "mobileApp"],
        }),
        id: integer("id").primaryKey(),
    },
    (columns) => ({
        orderIdx: index("products_sales_channels_order_idx").on(columns.order),
        parentIdx: index("products_sales_channels_parent_idx").on(
            columns.parent
        ),
        parentFk: foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [products.id],
            name: "products_sales_channels_parent_fk",
        }).onDelete("cascade"),
    })
);

export const products_variant_options = sqliteTable(
    "products_variant_options",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: text("id").primaryKey(),
        option: text("option").notNull(),
    },
    (columns) => ({
        _orderIdx: index("products_variant_options_order_idx").on(
            columns._order
        ),
        _parentIDIdx: index("products_variant_options_parent_id_idx").on(
            columns._parentID
        ),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [products.id],
            name: "products_variant_options_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const products_variants_options = sqliteTable(
    "products_variants_options",
    {
        _order: integer("_order").notNull(),
        _parentID: text("_parent_id").notNull(),
        id: text("id").primaryKey(),
        option: text("option").notNull(),
        value: text("value").notNull(),
    },
    (columns) => ({
        _orderIdx: index("products_variants_options_order_idx").on(
            columns._order
        ),
        _parentIDIdx: index("products_variants_options_parent_id_idx").on(
            columns._parentID
        ),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [products_variants.id],
            name: "products_variants_options_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const products_variants = sqliteTable(
    "products_variants",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: text("id").primaryKey(),
        vid: text("vid"),
        imageUrl: text("image_url"),
        price: numeric("price").notNull(),
        originalPrice: numeric("original_price"),
    },
    (columns) => ({
        _orderIdx: index("products_variants_order_idx").on(columns._order),
        _parentIDIdx: index("products_variants_parent_id_idx").on(
            columns._parentID
        ),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [products.id],
            name: "products_variants_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const products_custom_fields = sqliteTable(
    "products_custom_fields",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: text("id").primaryKey(),
        name: text("name").notNull(),
        value: text("value"),
    },
    (columns) => ({
        _orderIdx: index("products_custom_fields_order_idx").on(columns._order),
        _parentIDIdx: index("products_custom_fields_parent_id_idx").on(
            columns._parentID
        ),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [products.id],
            name: "products_custom_fields_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const products = sqliteTable(
    "products",
    {
        id: integer("id").primaryKey(),
        pid: text("pid"),
        title: text("title").notNull(),
        currency: text("currency"),
        visible: integer("visible", { mode: "boolean" }).default(true),
        source: text("source", { enum: ["manual", "cj"] }).default("manual"),
        description: text("description", { mode: "json" }),
        handle: text("handle"),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        products_handle_idx: index("products_handle_idx").on(columns.handle),
        products_updated_at_idx: index("products_updated_at_idx").on(
            columns.updatedAt
        ),
        products_created_at_idx: index("products_created_at_idx").on(
            columns.createdAt
        ),
    })
);

export const products_texts = sqliteTable(
    "products_texts",
    {
        id: integer("id").primaryKey(),
        order: integer("order").notNull(),
        parent: integer("parent_id").notNull(),
        path: text("path").notNull(),
        text: text("text"),
    },
    (columns) => ({
        orderParentIdx: index("products_texts_order_parent_idx").on(
            columns.order,
            columns.parent
        ),
        parentFk: foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [products.id],
            name: "products_texts_parent_fk",
        }).onDelete("cascade"),
    })
);

export const products_rels = sqliteTable(
    "products_rels",
    {
        id: integer("id").primaryKey(),
        order: integer("order"),
        parent: integer("parent_id").notNull(),
        path: text("path").notNull(),
        collectionsID: integer("collections_id"),
        mediaID: integer("media_id"),
    },
    (columns) => ({
        order: index("products_rels_order_idx").on(columns.order),
        parentIdx: index("products_rels_parent_idx").on(columns.parent),
        pathIdx: index("products_rels_path_idx").on(columns.path),
        products_rels_collections_id_idx: index(
            "products_rels_collections_id_idx"
        ).on(columns.collectionsID),
        products_rels_media_id_idx: index("products_rels_media_id_idx").on(
            columns.mediaID
        ),
        parentFk: foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [products.id],
            name: "products_rels_parent_fk",
        }).onDelete("cascade"),
        collectionsIdFk: foreignKey({
            columns: [columns["collectionsID"]],
            foreignColumns: [collections.id],
            name: "products_rels_collections_fk",
        }).onDelete("cascade"),
        mediaIdFk: foreignKey({
            columns: [columns["mediaID"]],
            foreignColumns: [media.id],
            name: "products_rels_media_fk",
        }).onDelete("cascade"),
    })
);

export const users_roles = sqliteTable(
    "users_roles",
    {
        order: integer("order").notNull(),
        parent: integer("parent_id").notNull(),
        value: text("value", { enum: ["admin", "customer"] }),
        id: integer("id").primaryKey(),
    },
    (columns) => ({
        orderIdx: index("users_roles_order_idx").on(columns.order),
        parentIdx: index("users_roles_parent_idx").on(columns.parent),
        parentFk: foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [users.id],
            name: "users_roles_parent_fk",
        }).onDelete("cascade"),
    })
);

export const users = sqliteTable(
    "users",
    {
        id: integer("id").primaryKey(),
        firstName: text("first_name"),
        lastName: text("last_name"),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        email: text("email").notNull(),
        resetPasswordToken: text("reset_password_token"),
        resetPasswordExpiration: text("reset_password_expiration").default(
            sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
        ),
        salt: text("salt"),
        hash: text("hash"),
        loginAttempts: numeric("login_attempts").default("0"),
        lockUntil: text("lock_until").default(
            sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
        ),
    },
    (columns) => ({
        users_updated_at_idx: index("users_updated_at_idx").on(
            columns.updatedAt
        ),
        users_created_at_idx: index("users_created_at_idx").on(
            columns.createdAt
        ),
        users_email_idx: uniqueIndex("users_email_idx").on(columns.email),
    })
);

export const media = sqliteTable(
    "media",
    {
        id: integer("id").primaryKey(),
        alt: text("alt").notNull(),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        url: text("url"),
        thumbnailURL: text("thumbnail_u_r_l"),
        filename: text("filename"),
        mimeType: text("mime_type"),
        filesize: numeric("filesize"),
        width: numeric("width"),
        height: numeric("height"),
        focalX: numeric("focal_x"),
        focalY: numeric("focal_y"),
    },
    (columns) => ({
        media_updated_at_idx: index("media_updated_at_idx").on(
            columns.updatedAt
        ),
        media_created_at_idx: index("media_created_at_idx").on(
            columns.createdAt
        ),
        media_filename_idx: uniqueIndex("media_filename_idx").on(
            columns.filename
        ),
    })
);

export const policies = sqliteTable(
    "policies",
    {
        id: integer("id").primaryKey(),
        title: text("title").notNull(),
        description: text("description", { mode: "json" }),
        handle: text("handle"),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        policies_handle_idx: index("policies_handle_idx").on(columns.handle),
        policies_updated_at_idx: index("policies_updated_at_idx").on(
            columns.updatedAt
        ),
        policies_created_at_idx: index("policies_created_at_idx").on(
            columns.createdAt
        ),
    })
);

export const gift_cards = sqliteTable(
    "gift_cards",
    {
        id: integer("id").primaryKey(),
        code: text("code").notNull(),
        value: numeric("value").notNull(),
        customer: integer("customer_id").references(() => users.id, {
            onDelete: "set null",
        }),
        expiryDate: text("expiry_date").default(
            sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
        ),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        gift_cards_customer_idx: index("gift_cards_customer_idx").on(
            columns.customer
        ),
        gift_cards_updated_at_idx: index("gift_cards_updated_at_idx").on(
            columns.updatedAt
        ),
        gift_cards_created_at_idx: index("gift_cards_created_at_idx").on(
            columns.createdAt
        ),
    })
);

export const payments_blocks_manual_provider_details = sqliteTable(
    "payments_blocks_manual_provider_details",
    {
        _order: integer("_order").notNull(),
        _parentID: text("_parent_id").notNull(),
        id: text("id").primaryKey(),
        label: text("label"),
        value: text("value"),
    },
    (columns) => ({
        _orderIdx: index(
            "payments_blocks_manual_provider_details_order_idx"
        ).on(columns._order),
        _parentIDIdx: index(
            "payments_blocks_manual_provider_details_parent_id_idx"
        ).on(columns._parentID),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [payments_blocks_manual_provider.id],
            name: "payments_blocks_manual_provider_details_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const payments_blocks_manual_provider = sqliteTable(
    "payments_blocks_manual_provider",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        _path: text("_path").notNull(),
        id: text("id").primaryKey(),
        providerName: text("provider_name"),
        methodType: text("method_type", {
            enum: ["cod", "bankTransfer", "inStore", "other"],
        }).notNull(),
        instructions: text("instructions").notNull(),
        blockName: text("block_name"),
    },
    (columns) => ({
        _orderIdx: index("payments_blocks_manual_provider_order_idx").on(
            columns._order
        ),
        _parentIDIdx: index("payments_blocks_manual_provider_parent_id_idx").on(
            columns._parentID
        ),
        _pathIdx: index("payments_blocks_manual_provider_path_idx").on(
            columns._path
        ),
        _parentIdFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [payments.id],
            name: "payments_blocks_manual_provider_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const payments_blocks_stripe = sqliteTable(
    "payments_blocks_stripe",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        _path: text("_path").notNull(),
        id: text("id").primaryKey(),
        stripeSecretKey: text("stripe_secret_key").notNull(),
        stripeWebhooksEndpointSecret: text(
            "stripe_webhooks_endpoint_secret"
        ).notNull(),
        publishableKey: text("publishable_key").notNull(),
        blockName: text("block_name"),
    },
    (columns) => ({
        _orderIdx: index("payments_blocks_stripe_order_idx").on(columns._order),
        _parentIDIdx: index("payments_blocks_stripe_parent_id_idx").on(
            columns._parentID
        ),
        _pathIdx: index("payments_blocks_stripe_path_idx").on(columns._path),
        _parentIdFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [payments.id],
            name: "payments_blocks_stripe_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const payments = sqliteTable(
    "payments",
    {
        id: integer("id").primaryKey(),
        name: text("name").notNull(),
        enabled: integer("enabled", { mode: "boolean" }),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        payments_updated_at_idx: index("payments_updated_at_idx").on(
            columns.updatedAt
        ),
        payments_created_at_idx: index("payments_created_at_idx").on(
            columns.createdAt
        ),
    })
);

export const locations = sqliteTable(
    "locations",
    {
        id: integer("id").primaryKey(),
        name: text("name").notNull(),
        address: text("address").notNull(),
        coordinates: text("coordinates", { mode: "json" }),
        contactPhone: text("contact_phone"),
        hours: text("hours"),
        enabled: integer("enabled", { mode: "boolean" }).default(true),
        isPickupLocation: integer("is_pickup_location", {
            mode: "boolean",
        }).default(false),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        locations_updated_at_idx: index("locations_updated_at_idx").on(
            columns.updatedAt
        ),
        locations_created_at_idx: index("locations_created_at_idx").on(
            columns.createdAt
        ),
    })
);

export const shipping_blocks_manual = sqliteTable(
    "shipping_blocks_manual",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        _path: text("_path").notNull(),
        id: text("id").primaryKey(),
        name: text("name").notNull(),
        rate: numeric("rate").notNull(),
        blockName: text("block_name"),
    },
    (columns) => ({
        _orderIdx: index("shipping_blocks_manual_order_idx").on(columns._order),
        _parentIDIdx: index("shipping_blocks_manual_parent_id_idx").on(
            columns._parentID
        ),
        _pathIdx: index("shipping_blocks_manual_path_idx").on(columns._path),
        _parentIdFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [shipping.id],
            name: "shipping_blocks_manual_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const shipping = sqliteTable(
    "shipping",
    {
        id: integer("id").primaryKey(),
        name: text("name").notNull(),
        enabled: integer("enabled", { mode: "boolean" }).default(true),
        location: integer("location_id").references(() => locations.id, {
            onDelete: "set null",
        }),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        shipping_location_idx: index("shipping_location_idx").on(
            columns.location
        ),
        shipping_updated_at_idx: index("shipping_updated_at_idx").on(
            columns.updatedAt
        ),
        shipping_created_at_idx: index("shipping_created_at_idx").on(
            columns.createdAt
        ),
    })
);

export const carts_cart_items = sqliteTable(
    "carts_cart_items",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: text("id").primaryKey(),
        product: integer("product_id")
            .notNull()
            .references(() => products.id, {
                onDelete: "set null",
            }),
        quantity: numeric("quantity").notNull(),
    },
    (columns) => ({
        _orderIdx: index("carts_cart_items_order_idx").on(columns._order),
        _parentIDIdx: index("carts_cart_items_parent_id_idx").on(
            columns._parentID
        ),
        carts_cart_items_product_idx: index("carts_cart_items_product_idx").on(
            columns.product
        ),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [carts.id],
            name: "carts_cart_items_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const carts = sqliteTable(
    "carts",
    {
        id: integer("id").primaryKey(),
        sessionId: text("session_id").notNull(),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        carts_updated_at_idx: index("carts_updated_at_idx").on(
            columns.updatedAt
        ),
        carts_created_at_idx: index("carts_created_at_idx").on(
            columns.createdAt
        ),
    })
);

export const cj_settings_items = sqliteTable(
    "cj_settings_items",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: text("id").primaryKey(),
        productUrl: text("product_url"),
    },
    (columns) => ({
        _orderIdx: index("cj_settings_items_order_idx").on(columns._order),
        _parentIDIdx: index("cj_settings_items_parent_id_idx").on(
            columns._parentID
        ),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [cj_settings.id],
            name: "cj_settings_items_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const cj_settings = sqliteTable(
    "cj_settings",
    {
        id: integer("id").primaryKey(),
        emailAddress: text("email_address"),
        apiToken: text("api_token"),
        refreshToken: text("refresh_token"),
        refreshTokenExpiry: text("refresh_token_expiry").default(
            sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
        ),
        accessToken: text("access_token"),
        accessTokenExpiry: text("access_token_expiry").default(
            sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
        ),
        pod: integer("pod_id").references(() => media.id, {
            onDelete: "set null",
        }),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        cj_settings_pod_idx: index("cj_settings_pod_idx").on(columns.pod),
        cj_settings_updated_at_idx: index("cj_settings_updated_at_idx").on(
            columns.updatedAt
        ),
        cj_settings_created_at_idx: index("cj_settings_created_at_idx").on(
            columns.createdAt
        ),
    })
);

export const plugins_space = sqliteTable(
    "plugins_space",
    {
        id: integer("id").primaryKey(),
        pluginName: text("plugin_name"),
        displayName: text("display_name"),
        pluginVersion: text("plugin_version"),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        plugins_space_updated_at_idx: index("plugins_space_updated_at_idx").on(
            columns.updatedAt
        ),
        plugins_space_created_at_idx: index("plugins_space_created_at_idx").on(
            columns.createdAt
        ),
    })
);

export const exports = sqliteTable(
    "exports",
    {
        id: integer("id").primaryKey(),
        name: text("name"),
        format: text("format", { enum: ["csv", "json"] })
            .notNull()
            .default("csv"),
        limit: numeric("limit"),
        sort: text("sort"),
        drafts: text("drafts", { enum: ["yes", "no"] }).default("yes"),
        collectionSlug: text("collection_slug").notNull(),
        where: text("where", { mode: "json" }).default("{}"),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        url: text("url"),
        thumbnailURL: text("thumbnail_u_r_l"),
        filename: text("filename"),
        mimeType: text("mime_type"),
        filesize: numeric("filesize"),
        width: numeric("width"),
        height: numeric("height"),
        focalX: numeric("focal_x"),
        focalY: numeric("focal_y"),
    },
    (columns) => ({
        exports_updated_at_idx: index("exports_updated_at_idx").on(
            columns.updatedAt
        ),
        exports_created_at_idx: index("exports_created_at_idx").on(
            columns.createdAt
        ),
        exports_filename_idx: uniqueIndex("exports_filename_idx").on(
            columns.filename
        ),
    })
);

export const exports_texts = sqliteTable(
    "exports_texts",
    {
        id: integer("id").primaryKey(),
        order: integer("order").notNull(),
        parent: integer("parent_id").notNull(),
        path: text("path").notNull(),
        text: text("text"),
    },
    (columns) => ({
        orderParentIdx: index("exports_texts_order_parent_idx").on(
            columns.order,
            columns.parent
        ),
        parentFk: foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [exports.id],
            name: "exports_texts_parent_fk",
        }).onDelete("cascade"),
    })
);

export const payload_jobs_log = sqliteTable(
    "payload_jobs_log",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: text("id").primaryKey(),
        executedAt: text("executed_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        completedAt: text("completed_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        taskSlug: text("task_slug", {
            enum: ["inline", "createCollectionExport"],
        }).notNull(),
        taskID: text("task_i_d").notNull(),
        input: text("input", { mode: "json" }),
        output: text("output", { mode: "json" }),
        state: text("state", { enum: ["failed", "succeeded"] }).notNull(),
        error: text("error", { mode: "json" }),
    },
    (columns) => ({
        _orderIdx: index("payload_jobs_log_order_idx").on(columns._order),
        _parentIDIdx: index("payload_jobs_log_parent_id_idx").on(
            columns._parentID
        ),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [payload_jobs.id],
            name: "payload_jobs_log_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const payload_jobs = sqliteTable(
    "payload_jobs",
    {
        id: integer("id").primaryKey(),
        input: text("input", { mode: "json" }),
        completedAt: text("completed_at").default(
            sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
        ),
        totalTried: numeric("total_tried").default("0"),
        hasError: integer("has_error", { mode: "boolean" }).default(false),
        error: text("error", { mode: "json" }),
        taskSlug: text("task_slug", {
            enum: ["inline", "createCollectionExport"],
        }),
        queue: text("queue").default("default"),
        waitUntil: text("wait_until").default(
            sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
        ),
        processing: integer("processing", { mode: "boolean" }).default(false),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        payload_jobs_completed_at_idx: index(
            "payload_jobs_completed_at_idx"
        ).on(columns.completedAt),
        payload_jobs_total_tried_idx: index("payload_jobs_total_tried_idx").on(
            columns.totalTried
        ),
        payload_jobs_has_error_idx: index("payload_jobs_has_error_idx").on(
            columns.hasError
        ),
        payload_jobs_task_slug_idx: index("payload_jobs_task_slug_idx").on(
            columns.taskSlug
        ),
        payload_jobs_queue_idx: index("payload_jobs_queue_idx").on(
            columns.queue
        ),
        payload_jobs_wait_until_idx: index("payload_jobs_wait_until_idx").on(
            columns.waitUntil
        ),
        payload_jobs_processing_idx: index("payload_jobs_processing_idx").on(
            columns.processing
        ),
        payload_jobs_updated_at_idx: index("payload_jobs_updated_at_idx").on(
            columns.updatedAt
        ),
        payload_jobs_created_at_idx: index("payload_jobs_created_at_idx").on(
            columns.createdAt
        ),
    })
);

export const payload_locked_documents = sqliteTable(
    "payload_locked_documents",
    {
        id: integer("id").primaryKey(),
        globalSlug: text("global_slug"),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        payload_locked_documents_global_slug_idx: index(
            "payload_locked_documents_global_slug_idx"
        ).on(columns.globalSlug),
        payload_locked_documents_updated_at_idx: index(
            "payload_locked_documents_updated_at_idx"
        ).on(columns.updatedAt),
        payload_locked_documents_created_at_idx: index(
            "payload_locked_documents_created_at_idx"
        ).on(columns.createdAt),
    })
);

export const payload_locked_documents_rels = sqliteTable(
    "payload_locked_documents_rels",
    {
        id: integer("id").primaryKey(),
        order: integer("order"),
        parent: integer("parent_id").notNull(),
        path: text("path").notNull(),
        ordersID: integer("orders_id"),
        collectionsID: integer("collections_id"),
        productsID: integer("products_id"),
        usersID: integer("users_id"),
        mediaID: integer("media_id"),
        policiesID: integer("policies_id"),
        "gift-cardsID": integer("gift_cards_id"),
        paymentsID: integer("payments_id"),
        locationsID: integer("locations_id"),
        shippingID: integer("shipping_id"),
        cartsID: integer("carts_id"),
        "cj-settingsID": integer("cj_settings_id"),
        "plugins-spaceID": integer("plugins_space_id"),
        exportsID: integer("exports_id"),
        "payload-jobsID": integer("payload_jobs_id"),
    },
    (columns) => ({
        order: index("payload_locked_documents_rels_order_idx").on(
            columns.order
        ),
        parentIdx: index("payload_locked_documents_rels_parent_idx").on(
            columns.parent
        ),
        pathIdx: index("payload_locked_documents_rels_path_idx").on(
            columns.path
        ),
        payload_locked_documents_rels_orders_id_idx: index(
            "payload_locked_documents_rels_orders_id_idx"
        ).on(columns.ordersID),
        payload_locked_documents_rels_collections_id_idx: index(
            "payload_locked_documents_rels_collections_id_idx"
        ).on(columns.collectionsID),
        payload_locked_documents_rels_products_id_idx: index(
            "payload_locked_documents_rels_products_id_idx"
        ).on(columns.productsID),
        payload_locked_documents_rels_users_id_idx: index(
            "payload_locked_documents_rels_users_id_idx"
        ).on(columns.usersID),
        payload_locked_documents_rels_media_id_idx: index(
            "payload_locked_documents_rels_media_id_idx"
        ).on(columns.mediaID),
        payload_locked_documents_rels_policies_id_idx: index(
            "payload_locked_documents_rels_policies_id_idx"
        ).on(columns.policiesID),
        payload_locked_documents_rels_gift_cards_id_idx: index(
            "payload_locked_documents_rels_gift_cards_id_idx"
        ).on(columns["gift-cardsID"]),
        payload_locked_documents_rels_payments_id_idx: index(
            "payload_locked_documents_rels_payments_id_idx"
        ).on(columns.paymentsID),
        payload_locked_documents_rels_locations_id_idx: index(
            "payload_locked_documents_rels_locations_id_idx"
        ).on(columns.locationsID),
        payload_locked_documents_rels_shipping_id_idx: index(
            "payload_locked_documents_rels_shipping_id_idx"
        ).on(columns.shippingID),
        payload_locked_documents_rels_carts_id_idx: index(
            "payload_locked_documents_rels_carts_id_idx"
        ).on(columns.cartsID),
        payload_locked_documents_rels_cj_settings_id_idx: index(
            "payload_locked_documents_rels_cj_settings_id_idx"
        ).on(columns["cj-settingsID"]),
        payload_locked_documents_rels_plugins_space_id_idx: index(
            "payload_locked_documents_rels_plugins_space_id_idx"
        ).on(columns["plugins-spaceID"]),
        payload_locked_documents_rels_exports_id_idx: index(
            "payload_locked_documents_rels_exports_id_idx"
        ).on(columns.exportsID),
        payload_locked_documents_rels_payload_jobs_id_idx: index(
            "payload_locked_documents_rels_payload_jobs_id_idx"
        ).on(columns["payload-jobsID"]),
        parentFk: foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [payload_locked_documents.id],
            name: "payload_locked_documents_rels_parent_fk",
        }).onDelete("cascade"),
        ordersIdFk: foreignKey({
            columns: [columns["ordersID"]],
            foreignColumns: [orders.id],
            name: "payload_locked_documents_rels_orders_fk",
        }).onDelete("cascade"),
        collectionsIdFk: foreignKey({
            columns: [columns["collectionsID"]],
            foreignColumns: [collections.id],
            name: "payload_locked_documents_rels_collections_fk",
        }).onDelete("cascade"),
        productsIdFk: foreignKey({
            columns: [columns["productsID"]],
            foreignColumns: [products.id],
            name: "payload_locked_documents_rels_products_fk",
        }).onDelete("cascade"),
        usersIdFk: foreignKey({
            columns: [columns["usersID"]],
            foreignColumns: [users.id],
            name: "payload_locked_documents_rels_users_fk",
        }).onDelete("cascade"),
        mediaIdFk: foreignKey({
            columns: [columns["mediaID"]],
            foreignColumns: [media.id],
            name: "payload_locked_documents_rels_media_fk",
        }).onDelete("cascade"),
        policiesIdFk: foreignKey({
            columns: [columns["policiesID"]],
            foreignColumns: [policies.id],
            name: "payload_locked_documents_rels_policies_fk",
        }).onDelete("cascade"),
        "gift-cardsIdFk": foreignKey({
            columns: [columns["gift-cardsID"]],
            foreignColumns: [gift_cards.id],
            name: "payload_locked_documents_rels_gift_cards_fk",
        }).onDelete("cascade"),
        paymentsIdFk: foreignKey({
            columns: [columns["paymentsID"]],
            foreignColumns: [payments.id],
            name: "payload_locked_documents_rels_payments_fk",
        }).onDelete("cascade"),
        locationsIdFk: foreignKey({
            columns: [columns["locationsID"]],
            foreignColumns: [locations.id],
            name: "payload_locked_documents_rels_locations_fk",
        }).onDelete("cascade"),
        shippingIdFk: foreignKey({
            columns: [columns["shippingID"]],
            foreignColumns: [shipping.id],
            name: "payload_locked_documents_rels_shipping_fk",
        }).onDelete("cascade"),
        cartsIdFk: foreignKey({
            columns: [columns["cartsID"]],
            foreignColumns: [carts.id],
            name: "payload_locked_documents_rels_carts_fk",
        }).onDelete("cascade"),
        "cj-settingsIdFk": foreignKey({
            columns: [columns["cj-settingsID"]],
            foreignColumns: [cj_settings.id],
            name: "payload_locked_documents_rels_cj_settings_fk",
        }).onDelete("cascade"),
        "plugins-spaceIdFk": foreignKey({
            columns: [columns["plugins-spaceID"]],
            foreignColumns: [plugins_space.id],
            name: "payload_locked_documents_rels_plugins_space_fk",
        }).onDelete("cascade"),
        exportsIdFk: foreignKey({
            columns: [columns["exportsID"]],
            foreignColumns: [exports.id],
            name: "payload_locked_documents_rels_exports_fk",
        }).onDelete("cascade"),
        "payload-jobsIdFk": foreignKey({
            columns: [columns["payload-jobsID"]],
            foreignColumns: [payload_jobs.id],
            name: "payload_locked_documents_rels_payload_jobs_fk",
        }).onDelete("cascade"),
    })
);

export const payload_preferences = sqliteTable(
    "payload_preferences",
    {
        id: integer("id").primaryKey(),
        key: text("key"),
        value: text("value", { mode: "json" }),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        payload_preferences_key_idx: index("payload_preferences_key_idx").on(
            columns.key
        ),
        payload_preferences_updated_at_idx: index(
            "payload_preferences_updated_at_idx"
        ).on(columns.updatedAt),
        payload_preferences_created_at_idx: index(
            "payload_preferences_created_at_idx"
        ).on(columns.createdAt),
    })
);

export const payload_preferences_rels = sqliteTable(
    "payload_preferences_rels",
    {
        id: integer("id").primaryKey(),
        order: integer("order"),
        parent: integer("parent_id").notNull(),
        path: text("path").notNull(),
        usersID: integer("users_id"),
    },
    (columns) => ({
        order: index("payload_preferences_rels_order_idx").on(columns.order),
        parentIdx: index("payload_preferences_rels_parent_idx").on(
            columns.parent
        ),
        pathIdx: index("payload_preferences_rels_path_idx").on(columns.path),
        payload_preferences_rels_users_id_idx: index(
            "payload_preferences_rels_users_id_idx"
        ).on(columns.usersID),
        parentFk: foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [payload_preferences.id],
            name: "payload_preferences_rels_parent_fk",
        }).onDelete("cascade"),
        usersIdFk: foreignKey({
            columns: [columns["usersID"]],
            foreignColumns: [users.id],
            name: "payload_preferences_rels_users_fk",
        }).onDelete("cascade"),
    })
);

export const payload_migrations = sqliteTable(
    "payload_migrations",
    {
        id: integer("id").primaryKey(),
        name: text("name"),
        batch: numeric("batch"),
        updatedAt: text("updated_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
        createdAt: text("created_at")
            .notNull()
            .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    },
    (columns) => ({
        payload_migrations_updated_at_idx: index(
            "payload_migrations_updated_at_idx"
        ).on(columns.updatedAt),
        payload_migrations_created_at_idx: index(
            "payload_migrations_created_at_idx"
        ).on(columns.createdAt),
    })
);

export const store_settings = sqliteTable("store_settings", {
    id: integer("id").primaryKey(),
    name: text("name").default("ShopLoad"),
    currency: text("currency", {
        enum: [
            "AED",
            "AFN",
            "ALL",
            "AMD",
            "ANG",
            "AOA",
            "ARS",
            "AUD",
            "AWG",
            "AZN",
            "BAM",
            "BBD",
            "BDT",
            "BGN",
            "BHD",
            "BIF",
            "BMD",
            "BND",
            "BOB",
            "BOV",
            "BRL",
            "BSD",
            "BTN",
            "BWP",
            "BYN",
            "BZD",
            "CAD",
            "CDF",
            "CHE",
            "CHF",
            "CHW",
            "CLF",
            "CLP",
            "CNY",
            "COP",
            "COU",
            "CRC",
            "CUC",
            "CUP",
            "CVE",
            "CZK",
            "DJF",
            "DKK",
            "DOP",
            "DZD",
            "EGP",
            "ERN",
            "ETB",
            "EUR",
            "FJD",
            "FKP",
            "GBP",
            "GEL",
            "GHS",
            "GIP",
            "GMD",
            "GNF",
            "GTQ",
            "GYD",
            "HKD",
            "HNL",
            "HTG",
            "HUF",
            "IDR",
            "ILS",
            "INR",
            "IQD",
            "IRR",
            "ISK",
            "JMD",
            "JOD",
            "JPY",
            "KES",
            "KGS",
            "KHR",
            "KMF",
            "KPW",
            "KRW",
            "KWD",
            "KYD",
            "KZT",
            "LAK",
            "LBP",
            "LKR",
            "LRD",
            "LSL",
            "LYD",
            "MAD",
            "MDL",
            "MGA",
            "MKD",
            "MMK",
            "MNT",
            "MOP",
            "MRU",
            "MUR",
            "MVR",
            "MWK",
            "MXN",
            "MXV",
            "MYR",
            "MZN",
            "NAD",
            "NGN",
            "NIO",
            "NOK",
            "NPR",
            "NZD",
            "OMR",
            "PAB",
            "PEN",
            "PGK",
            "PHP",
            "PKR",
            "PLN",
            "PYG",
            "QAR",
            "RON",
            "RSD",
            "RUB",
            "RWF",
            "SAR",
            "SBD",
            "SCR",
            "SDG",
            "SEK",
            "SGD",
            "SHP",
            "SLE",
            "SOS",
            "SRD",
            "SSP",
            "STN",
            "SVC",
            "SYP",
            "SZL",
            "THB",
            "TJS",
            "TMT",
            "TND",
            "TOP",
            "TRY",
            "TTD",
            "TWD",
            "TZS",
            "UAH",
            "UGX",
            "USD",
            "USN",
            "UYI",
            "UYU",
            "UYW",
            "UZS",
            "VED",
            "VES",
            "VND",
            "VUV",
            "WST",
            "XAF",
            "XAG",
            "XAU",
            "XBA",
            "XBB",
            "XBC",
            "XBD",
            "XCD",
            "XDR",
            "XOF",
            "XPD",
            "XPF",
            "XPT",
            "XSU",
            "XTS",
            "XUA",
            "XXX",
            "YER",
            "ZAR",
            "ZMW",
            "ZWG",
        ],
    }).default("USD"),
    updatedAt: text("updated_at").default(
        sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
    ),
    createdAt: text("created_at").default(
        sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
    ),
});

export const hero_section_blocks_hero = sqliteTable(
    "hero_section_blocks_hero",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        _path: text("_path").notNull(),
        id: text("id").primaryKey(),
        title: text("title").notNull(),
        subtitle: text("subtitle"),
        ctaButtonText: text("cta_button_text"),
        ctaButtonLink: text("cta_button_link"),
        backgroundImage: integer("background_image_id").references(
            () => media.id,
            {
                onDelete: "set null",
            }
        ),
        blockName: text("block_name"),
    },
    (columns) => ({
        _orderIdx: index("hero_section_blocks_hero_order_idx").on(
            columns._order
        ),
        _parentIDIdx: index("hero_section_blocks_hero_parent_id_idx").on(
            columns._parentID
        ),
        _pathIdx: index("hero_section_blocks_hero_path_idx").on(columns._path),
        hero_section_blocks_hero_background_image_idx: index(
            "hero_section_blocks_hero_background_image_idx"
        ).on(columns.backgroundImage),
        _parentIdFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [hero_section.id],
            name: "hero_section_blocks_hero_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const hero_section_blocks_carousel = sqliteTable(
    "hero_section_blocks_carousel",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        _path: text("_path").notNull(),
        id: text("id").primaryKey(),
        title: text("title").notNull(),
        subtitle: text("subtitle"),
        backgroundImage: integer("background_image_id").references(
            () => media.id,
            {
                onDelete: "set null",
            }
        ),
        blockName: text("block_name"),
    },
    (columns) => ({
        _orderIdx: index("hero_section_blocks_carousel_order_idx").on(
            columns._order
        ),
        _parentIDIdx: index("hero_section_blocks_carousel_parent_id_idx").on(
            columns._parentID
        ),
        _pathIdx: index("hero_section_blocks_carousel_path_idx").on(
            columns._path
        ),
        hero_section_blocks_carousel_background_image_idx: index(
            "hero_section_blocks_carousel_background_image_idx"
        ).on(columns.backgroundImage),
        _parentIdFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [hero_section.id],
            name: "hero_section_blocks_carousel_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const hero_section = sqliteTable("hero_section", {
    id: integer("id").primaryKey(),
    updatedAt: text("updated_at").default(
        sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
    ),
    createdAt: text("created_at").default(
        sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
    ),
});

export const hero_section_rels = sqliteTable(
    "hero_section_rels",
    {
        id: integer("id").primaryKey(),
        order: integer("order"),
        parent: integer("parent_id").notNull(),
        path: text("path").notNull(),
        mediaID: integer("media_id"),
    },
    (columns) => ({
        order: index("hero_section_rels_order_idx").on(columns.order),
        parentIdx: index("hero_section_rels_parent_idx").on(columns.parent),
        pathIdx: index("hero_section_rels_path_idx").on(columns.path),
        hero_section_rels_media_id_idx: index(
            "hero_section_rels_media_id_idx"
        ).on(columns.mediaID),
        parentFk: foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [hero_section.id],
            name: "hero_section_rels_parent_fk",
        }).onDelete("cascade"),
        mediaIdFk: foreignKey({
            columns: [columns["mediaID"]],
            foreignColumns: [media.id],
            name: "hero_section_rels_media_fk",
        }).onDelete("cascade"),
    })
);

export const footer_blocks_basic_footer = sqliteTable(
    "footer_blocks_basic_footer",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        _path: text("_path").notNull(),
        id: text("id").primaryKey(),
        copyright: text("copyright", { mode: "json" }).notNull(),
        poweredBy: text("powered_by", { mode: "json" }),
        blockName: text("block_name"),
    },
    (columns) => ({
        _orderIdx: index("footer_blocks_basic_footer_order_idx").on(
            columns._order
        ),
        _parentIDIdx: index("footer_blocks_basic_footer_parent_id_idx").on(
            columns._parentID
        ),
        _pathIdx: index("footer_blocks_basic_footer_path_idx").on(
            columns._path
        ),
        _parentIdFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [footer.id],
            name: "footer_blocks_basic_footer_parent_id_fk",
        }).onDelete("cascade"),
    })
);

export const footer = sqliteTable("footer", {
    id: integer("id").primaryKey(),
    updatedAt: text("updated_at").default(
        sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
    ),
    createdAt: text("created_at").default(
        sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`
    ),
});

export const relations_orders_items = relations(orders_items, ({ one }) => ({
    _parentID: one(orders, {
        fields: [orders_items._parentID],
        references: [orders.id],
        relationName: "items",
    }),
    product: one(products, {
        fields: [orders_items.product],
        references: [products.id],
        relationName: "product",
    }),
}));
export const relations_orders = relations(orders, ({ one, many }) => ({
    user: one(users, {
        fields: [orders.user],
        references: [users.id],
        relationName: "user",
    }),
    items: many(orders_items, {
        relationName: "items",
    }),
}));
export const relations_collections = relations(collections, () => ({}));
export const relations_products_sales_channels = relations(
    products_sales_channels,
    ({ one }) => ({
        parent: one(products, {
            fields: [products_sales_channels.parent],
            references: [products.id],
            relationName: "salesChannels",
        }),
    })
);
export const relations_products_variant_options = relations(
    products_variant_options,
    ({ one }) => ({
        _parentID: one(products, {
            fields: [products_variant_options._parentID],
            references: [products.id],
            relationName: "variantOptions",
        }),
    })
);
export const relations_products_variants_options = relations(
    products_variants_options,
    ({ one }) => ({
        _parentID: one(products_variants, {
            fields: [products_variants_options._parentID],
            references: [products_variants.id],
            relationName: "options",
        }),
    })
);
export const relations_products_variants = relations(
    products_variants,
    ({ one, many }) => ({
        _parentID: one(products, {
            fields: [products_variants._parentID],
            references: [products.id],
            relationName: "variants",
        }),
        options: many(products_variants_options, {
            relationName: "options",
        }),
    })
);
export const relations_products_custom_fields = relations(
    products_custom_fields,
    ({ one }) => ({
        _parentID: one(products, {
            fields: [products_custom_fields._parentID],
            references: [products.id],
            relationName: "customFields",
        }),
    })
);
export const relations_products_texts = relations(
    products_texts,
    ({ one }) => ({
        parent: one(products, {
            fields: [products_texts.parent],
            references: [products.id],
            relationName: "_texts",
        }),
    })
);
export const relations_products_rels = relations(products_rels, ({ one }) => ({
    parent: one(products, {
        fields: [products_rels.parent],
        references: [products.id],
        relationName: "_rels",
    }),
    collectionsID: one(collections, {
        fields: [products_rels.collectionsID],
        references: [collections.id],
        relationName: "collections",
    }),
    mediaID: one(media, {
        fields: [products_rels.mediaID],
        references: [media.id],
        relationName: "media",
    }),
}));
export const relations_products = relations(products, ({ many }) => ({
    salesChannels: many(products_sales_channels, {
        relationName: "salesChannels",
    }),
    variantOptions: many(products_variant_options, {
        relationName: "variantOptions",
    }),
    variants: many(products_variants, {
        relationName: "variants",
    }),
    customFields: many(products_custom_fields, {
        relationName: "customFields",
    }),
    _texts: many(products_texts, {
        relationName: "_texts",
    }),
    _rels: many(products_rels, {
        relationName: "_rels",
    }),
}));
export const relations_users_roles = relations(users_roles, ({ one }) => ({
    parent: one(users, {
        fields: [users_roles.parent],
        references: [users.id],
        relationName: "roles",
    }),
}));
export const relations_users = relations(users, ({ many }) => ({
    roles: many(users_roles, {
        relationName: "roles",
    }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_policies = relations(policies, () => ({}));
export const relations_gift_cards = relations(gift_cards, ({ one }) => ({
    customer: one(users, {
        fields: [gift_cards.customer],
        references: [users.id],
        relationName: "customer",
    }),
}));
export const relations_payments_blocks_manual_provider_details = relations(
    payments_blocks_manual_provider_details,
    ({ one }) => ({
        _parentID: one(payments_blocks_manual_provider, {
            fields: [payments_blocks_manual_provider_details._parentID],
            references: [payments_blocks_manual_provider.id],
            relationName: "details",
        }),
    })
);
export const relations_payments_blocks_manual_provider = relations(
    payments_blocks_manual_provider,
    ({ one, many }) => ({
        _parentID: one(payments, {
            fields: [payments_blocks_manual_provider._parentID],
            references: [payments.id],
            relationName: "_blocks_manualProvider",
        }),
        details: many(payments_blocks_manual_provider_details, {
            relationName: "details",
        }),
    })
);
export const relations_payments_blocks_stripe = relations(
    payments_blocks_stripe,
    ({ one }) => ({
        _parentID: one(payments, {
            fields: [payments_blocks_stripe._parentID],
            references: [payments.id],
            relationName: "_blocks_stripe",
        }),
    })
);
export const relations_payments = relations(payments, ({ many }) => ({
    _blocks_manualProvider: many(payments_blocks_manual_provider, {
        relationName: "_blocks_manualProvider",
    }),
    _blocks_stripe: many(payments_blocks_stripe, {
        relationName: "_blocks_stripe",
    }),
}));
export const relations_locations = relations(locations, () => ({}));
export const relations_shipping_blocks_manual = relations(
    shipping_blocks_manual,
    ({ one }) => ({
        _parentID: one(shipping, {
            fields: [shipping_blocks_manual._parentID],
            references: [shipping.id],
            relationName: "_blocks_manual",
        }),
    })
);
export const relations_shipping = relations(shipping, ({ one, many }) => ({
    location: one(locations, {
        fields: [shipping.location],
        references: [locations.id],
        relationName: "location",
    }),
    _blocks_manual: many(shipping_blocks_manual, {
        relationName: "_blocks_manual",
    }),
}));
export const relations_carts_cart_items = relations(
    carts_cart_items,
    ({ one }) => ({
        _parentID: one(carts, {
            fields: [carts_cart_items._parentID],
            references: [carts.id],
            relationName: "cartItems",
        }),
        product: one(products, {
            fields: [carts_cart_items.product],
            references: [products.id],
            relationName: "product",
        }),
    })
);
export const relations_carts = relations(carts, ({ many }) => ({
    cartItems: many(carts_cart_items, {
        relationName: "cartItems",
    }),
}));
export const relations_cj_settings_items = relations(
    cj_settings_items,
    ({ one }) => ({
        _parentID: one(cj_settings, {
            fields: [cj_settings_items._parentID],
            references: [cj_settings.id],
            relationName: "items",
        }),
    })
);
export const relations_cj_settings = relations(
    cj_settings,
    ({ one, many }) => ({
        pod: one(media, {
            fields: [cj_settings.pod],
            references: [media.id],
            relationName: "pod",
        }),
        items: many(cj_settings_items, {
            relationName: "items",
        }),
    })
);
export const relations_plugins_space = relations(plugins_space, () => ({}));
export const relations_exports_texts = relations(exports_texts, ({ one }) => ({
    parent: one(exports, {
        fields: [exports_texts.parent],
        references: [exports.id],
        relationName: "_texts",
    }),
}));
export const relations_exports = relations(exports, ({ many }) => ({
    _texts: many(exports_texts, {
        relationName: "_texts",
    }),
}));
export const relations_payload_jobs_log = relations(
    payload_jobs_log,
    ({ one }) => ({
        _parentID: one(payload_jobs, {
            fields: [payload_jobs_log._parentID],
            references: [payload_jobs.id],
            relationName: "log",
        }),
    })
);
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
    log: many(payload_jobs_log, {
        relationName: "log",
    }),
}));
export const relations_payload_locked_documents_rels = relations(
    payload_locked_documents_rels,
    ({ one }) => ({
        parent: one(payload_locked_documents, {
            fields: [payload_locked_documents_rels.parent],
            references: [payload_locked_documents.id],
            relationName: "_rels",
        }),
        ordersID: one(orders, {
            fields: [payload_locked_documents_rels.ordersID],
            references: [orders.id],
            relationName: "orders",
        }),
        collectionsID: one(collections, {
            fields: [payload_locked_documents_rels.collectionsID],
            references: [collections.id],
            relationName: "collections",
        }),
        productsID: one(products, {
            fields: [payload_locked_documents_rels.productsID],
            references: [products.id],
            relationName: "products",
        }),
        usersID: one(users, {
            fields: [payload_locked_documents_rels.usersID],
            references: [users.id],
            relationName: "users",
        }),
        mediaID: one(media, {
            fields: [payload_locked_documents_rels.mediaID],
            references: [media.id],
            relationName: "media",
        }),
        policiesID: one(policies, {
            fields: [payload_locked_documents_rels.policiesID],
            references: [policies.id],
            relationName: "policies",
        }),
        "gift-cardsID": one(gift_cards, {
            fields: [payload_locked_documents_rels["gift-cardsID"]],
            references: [gift_cards.id],
            relationName: "gift-cards",
        }),
        paymentsID: one(payments, {
            fields: [payload_locked_documents_rels.paymentsID],
            references: [payments.id],
            relationName: "payments",
        }),
        locationsID: one(locations, {
            fields: [payload_locked_documents_rels.locationsID],
            references: [locations.id],
            relationName: "locations",
        }),
        shippingID: one(shipping, {
            fields: [payload_locked_documents_rels.shippingID],
            references: [shipping.id],
            relationName: "shipping",
        }),
        cartsID: one(carts, {
            fields: [payload_locked_documents_rels.cartsID],
            references: [carts.id],
            relationName: "carts",
        }),
        "cj-settingsID": one(cj_settings, {
            fields: [payload_locked_documents_rels["cj-settingsID"]],
            references: [cj_settings.id],
            relationName: "cj-settings",
        }),
        "plugins-spaceID": one(plugins_space, {
            fields: [payload_locked_documents_rels["plugins-spaceID"]],
            references: [plugins_space.id],
            relationName: "plugins-space",
        }),
        exportsID: one(exports, {
            fields: [payload_locked_documents_rels.exportsID],
            references: [exports.id],
            relationName: "exports",
        }),
        "payload-jobsID": one(payload_jobs, {
            fields: [payload_locked_documents_rels["payload-jobsID"]],
            references: [payload_jobs.id],
            relationName: "payload-jobs",
        }),
    })
);
export const relations_payload_locked_documents = relations(
    payload_locked_documents,
    ({ many }) => ({
        _rels: many(payload_locked_documents_rels, {
            relationName: "_rels",
        }),
    })
);
export const relations_payload_preferences_rels = relations(
    payload_preferences_rels,
    ({ one }) => ({
        parent: one(payload_preferences, {
            fields: [payload_preferences_rels.parent],
            references: [payload_preferences.id],
            relationName: "_rels",
        }),
        usersID: one(users, {
            fields: [payload_preferences_rels.usersID],
            references: [users.id],
            relationName: "users",
        }),
    })
);
export const relations_payload_preferences = relations(
    payload_preferences,
    ({ many }) => ({
        _rels: many(payload_preferences_rels, {
            relationName: "_rels",
        }),
    })
);
export const relations_payload_migrations = relations(
    payload_migrations,
    () => ({})
);
export const relations_store_settings = relations(store_settings, () => ({}));
export const relations_hero_section_blocks_hero = relations(
    hero_section_blocks_hero,
    ({ one }) => ({
        _parentID: one(hero_section, {
            fields: [hero_section_blocks_hero._parentID],
            references: [hero_section.id],
            relationName: "_blocks_hero",
        }),
        backgroundImage: one(media, {
            fields: [hero_section_blocks_hero.backgroundImage],
            references: [media.id],
            relationName: "backgroundImage",
        }),
    })
);
export const relations_hero_section_blocks_carousel = relations(
    hero_section_blocks_carousel,
    ({ one }) => ({
        _parentID: one(hero_section, {
            fields: [hero_section_blocks_carousel._parentID],
            references: [hero_section.id],
            relationName: "_blocks_carousel",
        }),
        backgroundImage: one(media, {
            fields: [hero_section_blocks_carousel.backgroundImage],
            references: [media.id],
            relationName: "backgroundImage",
        }),
    })
);
export const relations_hero_section_rels = relations(
    hero_section_rels,
    ({ one }) => ({
        parent: one(hero_section, {
            fields: [hero_section_rels.parent],
            references: [hero_section.id],
            relationName: "_rels",
        }),
        mediaID: one(media, {
            fields: [hero_section_rels.mediaID],
            references: [media.id],
            relationName: "media",
        }),
    })
);
export const relations_hero_section = relations(hero_section, ({ many }) => ({
    _blocks_hero: many(hero_section_blocks_hero, {
        relationName: "_blocks_hero",
    }),
    _blocks_carousel: many(hero_section_blocks_carousel, {
        relationName: "_blocks_carousel",
    }),
    _rels: many(hero_section_rels, {
        relationName: "_rels",
    }),
}));
export const relations_footer_blocks_basic_footer = relations(
    footer_blocks_basic_footer,
    ({ one }) => ({
        _parentID: one(footer, {
            fields: [footer_blocks_basic_footer._parentID],
            references: [footer.id],
            relationName: "_blocks_basic-footer",
        }),
    })
);
export const relations_footer = relations(footer, ({ many }) => ({
    "_blocks_basic-footer": many(footer_blocks_basic_footer, {
        relationName: "_blocks_basic-footer",
    }),
}));

type DatabaseSchema = {
    orders_items: typeof orders_items;
    orders: typeof orders;
    collections: typeof collections;
    products_sales_channels: typeof products_sales_channels;
    products_variant_options: typeof products_variant_options;
    products_variants_options: typeof products_variants_options;
    products_variants: typeof products_variants;
    products_custom_fields: typeof products_custom_fields;
    products: typeof products;
    products_texts: typeof products_texts;
    products_rels: typeof products_rels;
    users_roles: typeof users_roles;
    users: typeof users;
    media: typeof media;
    policies: typeof policies;
    gift_cards: typeof gift_cards;
    payments_blocks_manual_provider_details: typeof payments_blocks_manual_provider_details;
    payments_blocks_manual_provider: typeof payments_blocks_manual_provider;
    payments_blocks_stripe: typeof payments_blocks_stripe;
    payments: typeof payments;
    locations: typeof locations;
    shipping_blocks_manual: typeof shipping_blocks_manual;
    shipping: typeof shipping;
    carts_cart_items: typeof carts_cart_items;
    carts: typeof carts;
    cj_settings_items: typeof cj_settings_items;
    cj_settings: typeof cj_settings;
    plugins_space: typeof plugins_space;
    exports: typeof exports;
    exports_texts: typeof exports_texts;
    payload_jobs_log: typeof payload_jobs_log;
    payload_jobs: typeof payload_jobs;
    payload_locked_documents: typeof payload_locked_documents;
    payload_locked_documents_rels: typeof payload_locked_documents_rels;
    payload_preferences: typeof payload_preferences;
    payload_preferences_rels: typeof payload_preferences_rels;
    payload_migrations: typeof payload_migrations;
    store_settings: typeof store_settings;
    hero_section_blocks_hero: typeof hero_section_blocks_hero;
    hero_section_blocks_carousel: typeof hero_section_blocks_carousel;
    hero_section: typeof hero_section;
    hero_section_rels: typeof hero_section_rels;
    footer_blocks_basic_footer: typeof footer_blocks_basic_footer;
    footer: typeof footer;
    relations_orders_items: typeof relations_orders_items;
    relations_orders: typeof relations_orders;
    relations_collections: typeof relations_collections;
    relations_products_sales_channels: typeof relations_products_sales_channels;
    relations_products_variant_options: typeof relations_products_variant_options;
    relations_products_variants_options: typeof relations_products_variants_options;
    relations_products_variants: typeof relations_products_variants;
    relations_products_custom_fields: typeof relations_products_custom_fields;
    relations_products_texts: typeof relations_products_texts;
    relations_products_rels: typeof relations_products_rels;
    relations_products: typeof relations_products;
    relations_users_roles: typeof relations_users_roles;
    relations_users: typeof relations_users;
    relations_media: typeof relations_media;
    relations_policies: typeof relations_policies;
    relations_gift_cards: typeof relations_gift_cards;
    relations_payments_blocks_manual_provider_details: typeof relations_payments_blocks_manual_provider_details;
    relations_payments_blocks_manual_provider: typeof relations_payments_blocks_manual_provider;
    relations_payments_blocks_stripe: typeof relations_payments_blocks_stripe;
    relations_payments: typeof relations_payments;
    relations_locations: typeof relations_locations;
    relations_shipping_blocks_manual: typeof relations_shipping_blocks_manual;
    relations_shipping: typeof relations_shipping;
    relations_carts_cart_items: typeof relations_carts_cart_items;
    relations_carts: typeof relations_carts;
    relations_cj_settings_items: typeof relations_cj_settings_items;
    relations_cj_settings: typeof relations_cj_settings;
    relations_plugins_space: typeof relations_plugins_space;
    relations_exports_texts: typeof relations_exports_texts;
    relations_exports: typeof relations_exports;
    relations_payload_jobs_log: typeof relations_payload_jobs_log;
    relations_payload_jobs: typeof relations_payload_jobs;
    relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
    relations_payload_locked_documents: typeof relations_payload_locked_documents;
    relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
    relations_payload_preferences: typeof relations_payload_preferences;
    relations_payload_migrations: typeof relations_payload_migrations;
    relations_store_settings: typeof relations_store_settings;
    relations_hero_section_blocks_hero: typeof relations_hero_section_blocks_hero;
    relations_hero_section_blocks_carousel: typeof relations_hero_section_blocks_carousel;
    relations_hero_section_rels: typeof relations_hero_section_rels;
    relations_hero_section: typeof relations_hero_section;
    relations_footer_blocks_basic_footer: typeof relations_footer_blocks_basic_footer;
    relations_footer: typeof relations_footer;
};

declare module "@payloadcms/db-sqlite/types" {
    export interface GeneratedDatabaseSchema {
        schema: DatabaseSchema;
    }
}
